
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css" href="./homestyle.css">
<style>
  body {
    font-family : Helvetica, sans-serif;
    margin: 0;
    
  }
  .header {
      padding: 60px;
      text-align: center;
      background: rgb(80, 16, 35);
      color: white;
      font-size: 35px;
    }
    h2 {text-align: center;}
    img {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 50%;
  }
  
  table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }
      
      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
      }
      
      tr:nth-child(even) {
        background-color: #dddddd;
      }
  
      .container {
    position: relative;
    font-family: Arial;
  }
  
  .text-block {
    position: absolute;
    bottom: 20px;
    right: 20px;
    background-color: black;
    color: white;
    padding-left: 20px;
    padding-right: 20px;
  }
  
  footer {
    text-align: center;
    padding: 3px;
    background-color: green;
    color: black;
  }

       
  
 
  

  
  </style>



</head>
<body>
<div class="header">
  <h1>Welcome To Tea Industry in Sri Lanka</h1>
</div>

<div class = "content" >
<img src="./hom1/tea1.jpg"  style="width: 100%" >
</div>

<h2><b>History of Ceylon Tea</b></h2>
<p>The story of Ceylon Tea begins with coffee. The tale begins in the early 1820s, barely five years after the surrender of Kandy, the last surviving indigenously-ruled state in Ceylon, to the British crown. By then, the rest of the island had already been a British colony for more than a generation. Its possession was considered vital to imperial interests in India and the Far East, but the cost of maintaining the military presence and infrastructure necessary to secure it was prohibitive. Attempts to raise revenue by taxation could not by themselves fill the gap; how to make the colony pay for itself and its garrison was a problem that had troubled successive governors since the first, Frederic North, took office in 1798.<p>
<p>Experiments with coffee may already have begun by 1824, when the fifth of Ceylon’s colonial governors, Edward Barnes, arrived in the island, but it was he who first saw in coffee a solution to the colony’s perennial balance-of-payments problem. The plant had already been found growing naturally among the approaches to the central hill country; sensing an opportunity, Barnes threw the weight of official support behind large-scale cultivation. Land in the central hills was sold for a few pence an acre, official funds were dedicated to research and experiments in coffee-growing, planters and merchants were provided with incentives and support. Most important of all, Barnes provided the infrastructure – a network of roads, including the all-important trunk route from Kandy to Colombo – that enabled coffee-planters to get their produce to town, and thence to market in England</p>
<img src="./hom1/t2.jpg"  style="width: 25%";>
<p>Barnes’ term of office ended in 1831. By then the coffee ‘enterprise’ (today we would call it an industry) occupied much of the country round Kandy and was spreading southward and upward into the formerly virgin forests of the central hills. Then, in 1838, the abolition of slavery in Jamaica caused the collapse of that country’s coffee industry. The resulting boom in Ceylon coffee opened up much that remained of the hitherto trackless hill country.
Despite setbacks in the late 1840s, the enterprise continued to grow. In the mid-1870s Ceylon became the world’s largest producer of coffee. Profits and revenues generated by the enterprise turned the colony into an imperial showpiece, prosperous, civilized and modern. Railways threaded the coffee-clad hillsides, roads plumbed the interior; the city of Colombo was gas-lit and its port had been developed with a breakwater and new quays. An effective government and civil administration kept things functioning smoothly, although the people of Ceylon had little say in either institution.</p>

<h2> <i>Sri Lanka Tea Production (MT) </i></h2>

<table>
  <tr>
    <th>Statistics</th>
    <th>2017</th>
    <th>2018</th>
    <th>2019</th>
    <th>2020</th>
    <th>2021</th>
  </tr>
  <tr>
    <td>Orthodox</td>
    <td>282,662</td>
    <td>277,340</td>
    <td>273,907</td>
    <td>252,367</td>
    <td>270,571</td>
    
  </tr>
  <tr>
  <td>CTC</td>
  <td>21,794</td>
  <td>23,902</td>
  <td>23,585</td>
  <td>24,099</td>
  <td>26,195</td>                                 
   
  </tr>
  <tr>
    <td>Green</td>
    <td>2,572</td>
    <td>2,624</td>
    <td>2,601</td>
    <td>2,642</td>
    <td>2,023</td>
  </tr>
  <tr>
    <td>Total</td>
    <td>307,080</td>
    <td>303,843</td>
    <td>300,134</td>
    <td>278,489</td>
    <td>299,338</td>
  </tr>
</table>
<br>

<h4><b>Top Tea companies in Sri Lanka</b></h4>
<p>1.Bogawantalawa Tea Ceylon (Pvt) Ltd</p>
<p>2.Sri Lanka Tea Board</p>
<p>3.Green island marketing Services (Pvt) Ltd</p>
<p>4.Venture Tea (Pvt) Ltd</p>
<p>5.Amazon Teas</p>
<p>6.Empire Teas (Pvt) Ltd</p>
<p>7.Dilmah</p>
<p>8.Heritage Teas (Pvt) Ltd </p>
<p>9.Minah Tea Exports (Pvt) Ltd</p>
<p>10.ANVERALLY</p>

<h2> <i> Few Tea Factories in Sri Lanka </i> </h2>
<div class="container">
  <img src="./hom1/kad.jpg" alt="Nature" style="width:100%;">
  <div class="text-block">
    <h4>Kadugannawa Tea Factory</h4>
    <p>Enjoy free breakfast, free WiFi and free parking. Popular attractions Kadugannawa Tea Factory & Sales Center</p>
  </div>
</div>

<div class="container">
  <img src="./hom1/han1.jpg" alt="Nature" style="width:100%;">
  <div class="text-block">
    <h4>Hanthana Tea Factory</h4>
    <p>Hanthana Tea Museum provides a good history of tea cultivation in Sri Lanka. You can get a guided tour</p>
  </div>
</div>

<div class="container">
  <img src="./hom1/tal.jpg" alt="Nature" style="width:100%;">
  <div class="text-block">
    <h4>Talawakelle Tea Factory</h4>
    <p>Talawakelle Tea Estates PLC produces high quality black tea in seventeen tea gardens situated in the best tea growing areas</p>
  </div>
</div>

<br>
<footer>
<div class="footer-copyright text-center py-3">© 2022 Copyright: 
    <a href="https://www.srilankateaboard.lk/"> Visit for More</a>
  </div>
</footer>

</body>
</html>
